file:
  directory: /home/download

spring:
  datasource:
    url: jdbc:log4jdbc:mariadb://192.168.0.144/db_even_first_5
    username: even_first_5
    password: gggg
  jpa:
    hibernate:
      ddl-auto: none
